os: 
  - Visual Studio 2015
  - Visual Studio 2013

platform:
  - Win32
  - Win64

before_build:
  - cmd: curl -fsSL https://github.com/tboox/xmake/releases/download/v2.0.5/xmake-v2.0.5.exe -o xmake-installer.exe
  - cmd: xmake-installer.exe /S 
  - cmd: xmake --version

build_script:
  - cmd: xmake
  - cmd: xmake p
  - cmd: if %platform%==Win32 xmake f -m debug
  - cmd: if %platform%==Win64 xmake f -m debug -a x64
  - cmd: xmake -r

test_script:
  - cmd: xmake r demo
